#pragma once

//GOOMBA
#define GOOMBA_WALKING_SPEED 0.05f*2
#define GOOMBA_GRAVITY 0.006f

#define GOOMBA_BEING_ATTACKED_SPEED_X 0.25f*2
#define GOOMBA_BEING_ATTACKED_SPEED_Y 0.65f*2

#define GOOMBA_BBOX_WIDTH 48
#define GOOMBA_BBOX_HEIGHT 45
#define GOOMBA_BBOX_HEIGHT_DIE 27


//KOOPAS
#define KOOPAS_BEING_KICK_SPEED 0.08f*4;
#define KOOPAS_WALKING_SPEED 0.08f;
#define KOOPAS_GRAVITY 0.006f

#define KOOPAS_BEING_ATTACKED_SPEED_X 0.25f*2
#define KOOPAS_BEING_ATTACKED_SPEED_Y 0.65f*2

#define KOOPAS_BBOX_WIDTH 16*3
#define KOOPAS_BBOX_HEIGHT 26*3
#define KOOPAS_BBOX_HEIGHT_COUCH 16*3

// Red_Goomba
#define RED_GOOMBA_BEING_KICK_SPEED 0.08f*4;
#define RED_GOOMBA_WALKING_SPEED 0.08f;
#define RED_GOOMBA_GRAVITY 0.006f

#define RED_GOOMBA_BEING_ATTACKED_SPEED_X 0.25f*2
#define RED_GOOMBA_BEING_ATTACKED_SPEED_Y 0.65f*2

#define RED_GOOMBA_BBOX_WIDTH 16*3
#define RED_GOOMBA_BBOX_HEIGHT 45
#define RED_GOOMBA_BBOX_HEIGHT_DIE 27

//PARA_Goomba
#define PARA_BEING_KICK_SPEED 0.08f*4;
#define PARA_WALKING_SPEED 0.08f;
#define PARA_GRAVITY 0.006f

#define PARA_HIGHT_JUMP_SPEED_Y 0.65f*2
#define PARA_JUMP_SPEED_Y 0.35f

#define PARA_BBOX_WIDTH 16*3
#define PARA_BBOX_HEIGHT 53
#define PARA_BBOX_FLY_HEIGHT 60

//VENUS_RED
#define VENUS_BBOX_WIDTH 48
#define VENUS_BBOX_HEIGHT 48*2

