#pragma once

//#define MARIO_WALKING_SPEED		0.15f 
//0.1f
#define MARIO_GRAVITY			0.00118f
#define MARIO_FRICTION			0.0075f

#define VELOCITY_Y_SPEEDUP_MAX		0.3f
#define VELOCITY_Y_SPEEDUP		0.2f
#define MARIO_JUMP_DEFLECT_SPEED 0.35f
#define VELOCITY_X_SPEEDUP_MAX  0.48f
#define VELOCITY_X_MAX          0.32f//0.00255f//0.32f
#define MARIO_DIE_DEFLECT_SPEED	 0.5f
#define MARIO_FLY_SPEED_Y				0.21f
#define MARIO_JUMP_SPEED_Y				0.49f
#define MARIO_HIGH_JUMP_SPEED_Y			0.63

#define MARIO_ACCELERATION_WALK     0.00115f
#define MARIO_ACCELERATION_RUN     0.01f
#define MARIO_ACCELERATION_DIE     0.02f

#define MARIO_STATE_DIE				400


#define KEYBOARD_PRESS_A			361
#define KEYBOARD_PRESS_LEFT			362
#define KEYBOARD_PRESS_RIGHT		363
#define KEYBOARD_PRESS_UP			366
#define KEYBOARD_PRESS_DOWN		    367
#define KEYBOARD_PRESS_TOP			364
#define KEYBOARD_PRESS_BOTTOM		365
#define KEYBOARD_PRESS_X			370
#define KEYBOARD_PRESS_S			371







#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_RACCOON		3
#define	MARIO_LEVEL_FIRE		4
#define	MARIO_LEVEL_FROG		5
#define	MARIO_LEVEL_TANOOKI		6
#define	MARIO_LEVEL_HAMMER		7

#define MARIO_SMALL_BBOX_WIDTH  12*3
#define MARIO_SMALL_BBOX_HEIGHT 15*3

#define MARIO_BIG_BBOX_WIDTH  15*3
#define MARIO_BIG_BBOX_HEIGHT 27*3

#define MARIO_FROG_BBOX_WIDTH  21*3
#define MARIO_FROG_BBOX_HEIGHT 24*3
#define MARIO_FROG_BBOX_HEIGHT_NOT_IDLE 31*3

#define MARIO_TANOOKI_BBOX_WIDTH  21*3
#define MARIO_TANOOKI_BBOX_HEIGHT 29*3
#define MARIO_TANOOKI_BBOX_WIDTH_NOT_IDLE  23*3

#define MARIO_RACCOON_BBOX_WIDTH  15*3-3
#define MARIO_RACCOON_BBOX_HEIGHT 28*3



#define MARIO_UNTOUCHABLE_TIME 5000

// MARIO_SELECTION_SCENCE
#define MARIO_SELECTION_VELOCITY          0.2f